[project]
name = "srt"
version = "0.1.0"
description = "Social Robotic Telesscope"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astral>=3.2",
    "astroplan>=0.10.1",
    "astropy>=7.2.0",
    "astroquery>=0.4.11",
    "mastodon-py>=2.1.4",
    "matplotlib>=3.10.8",
    "photutils>=2.3.0",
    "python-kasa",
    "pytz>=2025.2",
    "requests>=2.32.5",
    "opencv-python>=4.11.0",
    "paho-mqtt>=2.1.0",
]

[tool.uv.sources]
python-kasa = { path = "kasa_local", editable = true }
