"""Generate the state diagrams FROM the transition tables.

The diagram is not documentation of the machine; it is a projection of it.
docs/night_machine.mmd and docs/target_machine.mmd are committed, and CI
regenerates them and fails on any diff — so the pictures in the docs cannot
drift from the code, because they are the code.

    python scripts/gen_state_diagrams.py            # write docs/*.mmd
    python scripts/gen_state_diagrams.py --check    # exit 1 if stale (CI)
"""
import os
import sys

if __package__ is None or __package__ == "":
    _root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    if _root not in sys.path:
        sys.path.insert(0, _root)

from iris.core.machine import HOLD_STATES, INITIAL_STATE, STATES, TRANSITIONS
from iris.core.target_machine import (TARGET_INITIAL_STATE, TARGET_STATES,
                                      TARGET_TRANSITIONS)

HEADER = ("%% GENERATED by scripts/gen_state_diagrams.py -- DO NOT EDIT.\n"
          "%% CI regenerates this and fails if it differs from the table.\n")


def _mermaid(states, transitions, initial, holds=frozenset()):
    lines = [HEADER, "stateDiagram-v2"]
    lines.append(f"    [*] --> {initial}")
    for row in transitions:
        label = row.event
        if row.guards:
            label += " / " + " & ".join(g.__name__ for g in row.guards)
        if row.src == "*":
            # A wildcard row is drawn once from a synthetic 'any' node rather
            # than as an edge from every state, which would bury the diagram.
            lines.append(f"    note left of {row.dst}: from any non-hold state on {label}")
        else:
            lines.append(f"    {row.src} --> {row.dst}: {label}")
    for h in sorted(holds):
        lines.append(f"    note right of {h}: HOLD -- operator exit only")
    return "\n".join(lines) + "\n"


def render():
    docs = os.path.join(os.path.dirname(__file__), "..", "docs")
    out = {
        os.path.join(docs, "night_machine.mmd"):
            _mermaid(STATES, TRANSITIONS, INITIAL_STATE, HOLD_STATES),
        os.path.join(docs, "target_machine.mmd"):
            _mermaid(TARGET_STATES, TARGET_TRANSITIONS, TARGET_INITIAL_STATE),
    }
    return {os.path.abspath(k): v for k, v in out.items()}


def main():
    check = "--check" in sys.argv
    stale = []
    for path, content in render().items():
        current = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as fh:
                current = fh.read()
        if current != content:
            if check:
                stale.append(path)
            else:
                with open(path, "w", encoding="utf-8", newline="\n") as fh:
                    fh.write(content)
                print("wrote", os.path.relpath(path))
        else:
            print("up to date", os.path.relpath(path))
    if check and stale:
        print("STALE diagrams (regenerate with scripts/gen_state_diagrams.py):")
        for p in stale:
            print("  ", os.path.relpath(p))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
